name: Cosmin-Test

on:
  push:
    branches:
      - 'cosmin-test-1'   

      
jobs:
  build:
    name: Cosmin-Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:

      test1: australia
      test2: usa

      test3: cosmin


    steps:

     - name: Setup Env Vars

       run: |
        if [[ ${{ env.test3 }} == "cosmin" ]] ; then
          echo "VAR=${{ env.test1 }}" >> $GITHUB_ENV
        elif [[ ${{ steps.extract_branch.outputs.branch }} == "usa" ]] ; then
          echo "VAR=${{ env.test2}}" >> $GITHUB_ENV
        fi

     - name: Echo var
       id: check-var
       run: |
         echo "The commit message was ${{ env.VAR }}"
