name: Cosmin-Test

on:
  push:
    branches:
      - 'cosmin-test-1'   

      
jobs:
  build:
    name: Cosmin-Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:

      test1: australia
      test2: usa

    steps:

     - name: Echo var
       id: check-var
       run: |
         echo "The commit message was ${{ github.event.head_commit.message }}"
