name: Cosmin-Test

on:
  push:
    branches:
      - 'cosmin-test-1'                  

      
jobs:
  build:
    name: Cosmin-Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:

      test1: australia
      test2: usa


    steps:

     - name: Setup Env Vars
       run: |
        if [[ ${{ github.event.head_commit.message }} == 'australia' ]] ; then
          echo "VAR=${{ env.test1 }}" >> $GITHUB_ENV
        elif [[ ${{ github.event.head_commit.message }} == 'usa' ]] ; then
          echo "VAR=${{ env.test2}}" >> $GITHUB_ENV
        fi

     - name: Echo var
       id: check-var
       run: |
         echo "Based on the commit message this pipeline should run for region: ${{ env.VAR }}"