name: Cosmin-Test

on:
  push:
    branches:
      - 'cosmin-test-1'   

      
jobs:
  build:
    name: Cosmin-Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:

      test1: australia
      test2: usa


    steps:

     - name: Extract branch name
       shell: bash
       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
       id: extract_branch

     - name: Setup Env Vars

       run: |
        if [[ ${{ steps.extract_branch.outputs.branch }} == 'cosmin-test-1' ]] ; then
          echo "VAR=${{ env.test1 }}" >> $GITHUB_ENV
        elif [[ ${{ steps.extract_branch.outputs.branch }} == 'cosmin-test-2' ]] ; then
          echo "VAR=${{ env.test2}}" >> $GITHUB_ENV
        fi

     - name: Echo var
       id: check-var
       run: |
         echo ${{ env.VAR }}